### ISSUE TITLE
Somewhat confusing what "This metric ... is sent by receiver" means.

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#107]
Take `firCount` as an example, which is a count of Full Intra Request frames. If I understand correctly:

- For an incoming RTP stream, there will be an `RTCInboundRTPStreamStats` where `firCount` represents the number of FIR frames sent by the RtpReceiver.
- For an outgoing RTP stream, there will be an `RTCOutboundRTPStreamStats` where `firCount` represents the number of FIR frames received by the RtpSender.

This wasn't immediately obvious to me. Could we instead say:

"Counts the total number of Full Intra Request (FIR) packets received by the `RtpSender` (if this is an `RTCOutboundRTPStreamStats`) or sent by the `RtpReceiver` (if this is an `RTCInboundRTPStreamStats`)"?

Or something along those lines?

**Comment by taylor-b** [comment]
I just noticed we do this sort of thing further down for `qpSum`: "The count of frames is in framesDecoded for inbound stream stats, and in framesEncoded for outbound stream stats."

**Comment by alvestrand** [comment]
Hm. I don't like parentheses.... A FIR is observable at both ends of a track, but it's possible that some FIRs are lost in transit, so the counts may be different.

So we have:

- FIR at the track sender, which is observable by counting incoming FIR packets, represented in the RTCOutboundRTPStreamStats object with remote=false
- FIR at the track receiver, which is observable by counting outgoing FIR packets, represented in the RTCInboundRTPStreamStats object with remote=false

I don't think FIR count is reported using RTCP, so this stat won't be present if remote=true (although I'm sure @vr000m will correct me if I'm wrong).

The qpSum language actually had a different purpose, since you had to divide the sum by different numbers to get the average qp in the two cases, but yes, language like this ought to be a standard phrase.

**Comment by vr000m** [comment]
Over taken by events? we have remote stats:
> remote-inbound-rtp
Statistics for the remote endpoint's inbound RTP stream corresponding to an outbound stream that is currently sent with this RTCPeerConnection object. It is measured at the remote endpoint and reported in an RTCP Receiver Report (RR) or RTCP Extended Report (XR). It is accessed by the RTCRemoteInboundRTPStreamStats.

> remote-outbound-rtp
Statistics for the remote endpoint's outbound RTP stream corresponding to an inbound stream that is currently received with this RTCPeerConnection object. It is measured at the remote endpoint and reported in an RTCP Sender Report (SR). It is accessed by the RTCRemoteOutboundRTPStreamStats.
