### ISSUE TITLE
Track stats: track or attachment?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#130]
In implementation discussions, it was asked what the stats for a track mean for the case where a track is attached to a PC multiple times.

This is not possible using AddTrack, but is possible using ReplaceTrack or AddTransceiver.
The WG has previously said that this is "no special treatment" - if you ask for a track to be sent twice, it will be sent twice, and surface at the receiver as two tracks.

The cleanest way out seems to be to say that the track stats track the attachment of the track to an RTCPeerConnection, so that the sequence

pc.addTransceiver(track=a)
pc.addTransceiver(track=a)
pc.getStats(a)

will return a stats object with two RTCMediaStreamTrackStats objects in it.
For receivers, there is no such discrepancy, because a track is always sourced from a single receiver, and can't be detached from it.

@taylor-b @henbos @jan-ivar - comments requested.

**Comment by jan-ivar** [comment]
It seems to me selectors are tracks mostly because we added them before we had senders and receivers, but that may be ground we've already covered?

Btw, without using a selector, how would I locate a particular track in an RTCStatsReport today?

**Comment by henbos** [comment]
I like this idea. Supposedly the caller cares about a track and all of its attachments and this gives that, per-attachment track stats. It also means that the change to the spec and implementations are minor since the dictionary does not have to change.

Whether or not we want RTP sender/receiver stats I don't think that can cover per-track stats since a sender can change which track it is using and that could happen in-between calls to getStats and track stats accumulate over time. Even if possible that sounds like a really big hassle for a caller interested in tracks.

@jan-ivar The RTCMediaStreamTrackStats.trackIdentifier[1] will have the value of MediaStreamTrack.id[2]. If we have one RTCMediaStreamTrackStats per attachment, the multiple attachment case would mean multiple stats objects have the same trackIdentifier.

[1] http://rawgit.com/w3c/webrtc-stats/master/webrtc-stats.html#dom-rtcmediastreamtrackstats-trackidentifier
[2] https://www.w3.org/TR/mediacapture-streams/#widl-MediaStreamTrack-id

**Comment by alvestrand** [comment]
History: We added selectors to the spec because we thought they'd be useful, and added tracks as a selector because that was the only clear case we could think of at that moment. The discussion tended to say "this will become an union, but since we only have one case now, we'll specify that case".

**Comment by alvestrand** [comment]
I'm concluding from this thread (and offline discussions with @henbos and others) that we rephrase the spec to say that RTCMediaStreamTrackStats is a per-attachment statistic. I'll make the PR.
