### ISSUE TITLE
Are the stats read-only snapshots or will they change kept around?

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/webrtc-stats#136]
I was having trouble understanding whether stats objects can be changed after they are pulled via getStats. I assert that they should be well defined as either being snapshotted when getStats is called OR as being updated over time.

**Comment by jan-ivar** [comment]
I assume you're referring to the objects in the `RTCStatsReport` map. See https://github.com/w3c/webrtc-stats/issues/137.

These were always meant to be writable copies of data, i.e. dictionary semantics, where you get new objects each time.

This was apparent in [early versions of the spec](https://w3c.github.io/webrtc-pc/archives/20150922/webrtc.html#rtcstatsreport-object). Unfortunately, that WebIDL was broken, because dictionaries don't support inheritance, so we were forced to switch to using `object`, leading to the confusion you're pointing out. You're right we probably need prose to make up for this.
