### ISSUE TITLE
Unclear which framerate "framePerSecond" represents

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#141]
Current definition is: "It represents the nominal FPS value."

But we're unclear on which FPS value this is referring to. Is it the video source's, the MediaStreamTrack's, or the RtpSender's? Example:

1. Camera produces 60 frames per second.
2. MediaStreamTrack constraints bring it down to 30.
3. RtpSender parameters (degradation preferences or maxFramerate) bring it down further, to 15.

What should go in framesPerSecond? 60, 30 or 15? @vr000m, do you remember what the original intention was?

**Comment by alvestrand** [comment]
Note - it is presently attached to the RTCRTPMediaStreamStats, which exists once per simulcast stream. I remember thinking that when the "main" stream is configured for 60 fps, and the "secondary" is configured for 15 fps (4x degradation), the values would be 60 and 15 respectively, even if the "main" stream is not sending this fast (for whatever reason it might find to slow down - perhaps there aren't that many incoming frames).

**Comment by gunnarhm** [comment]
It can also be
4. Really achieved frame rate. 

And there should be two figures, one for sending and one for receiving. 

The name "Nominal ..." indicates however that it is not the really achieved framerate. 
I suggest that 4 values are provided with different names:
Nominal transmit frame rate (after all negotiations, that is figure 3 for transmission )
Nominal receive frame rate (after all negotiations, that is figure 3 for reception)
Really achieved mean transmitted frame rate.
Really achieved mean received frame rate.

**Comment by alvestrand** [comment]
I must correct myself: FrameRate (nominal) attaches to  RTCMediaStreamTrackStats. There are no frame-related stats connected to RTPStreams.

MediaStreamTracks are unidirectional, so there's only one frame rate. Outgoing and incoming frame rates (if we have both) are on different tracks.
Stat values should normally not be averages - see the discussion at http://rawgit.com/w3c/webrtc-stats/master/webrtc-stats.html#guidelines-for-design-of-stats-objects (I don't think we've published a dated editor's draft since this was merged). We already have frame counts at multiple levels.

**Comment by taylor-b** [comment]
> Nominal receive frame rate (after all negotiations, that is figure 3 for reception)

Since this isn't signaled explicitly in SDP, I think this would only make sense for codecs that put a framerate in the actual bitstream, such as H.264 (https://cardinalpeak.com/blog/the-h-264-sequence-parameter-set/)

> Really achieved mean transmitted/received frame rate.

This is already obtainable using `framesSent` and `framesReceived`.

**Comment by alvestrand** [comment]
The information about what's actually being sent seems to be available elsewhere.
It seems to me that what makes sense here is the framerate that the track has been configured to try to achieve - that is, either the selected camera framerate or the framerate that the rate adapter in the video pipeline is configured to try to achieve.
I think real framerate shouldn't ever go above this number, but may go below it for a number of reasons (CPU starvation, low light, congestion backpressure leading to dynamic reconfiguration...)

**Comment by alvestrand** [comment]
and unless a=framerate is present on an incoming track, or constraints are used to tell the infrastructure to adapt the incoming track to a lower framerate, I don't think the value makes sense to represent on a non-local track at all. It should be allowed to be omitted.

**Comment by henbos** [comment]
To echo what has already been said,
- Actual achieved framerate is already achievable with framesSent and framesReceived or framesDecoded (which may be lower than framesReceived due to incorrectly decoded frames or frames dropped on the way to the decoder - can that happen?).
- This should be configured frame rate.

So, for "configured framerate", we are either talking about:
- "Target framerate": the lowest value of all or some of: a=framerate, track configuration and RtpSender's maxFramerate.
- Adapted (degraded) framerate; what the encoder or decoder is currently using.

I expect the adapted framerate is already obtainable by RTC[In/Out]boundRTPStreamStats.frames[Encoded/Decoded].

So "target framerate" it is. How about something like?

> Only valid for video. It represents the nominal FPS value. This is the configured framerate for this track attachment to the RTCPeerConnection. It is limited by track constraints and a=framerate in SDP. Local tracks may also be limited by encoding parameters (see RTCRtpEncodingParameters.maxFramerate).

Assuming a=framerate and track constraints are two different things? Or is a=framerate what the track was constrained to use?

**Comment by taylor-b** [comment]
As I understand, "a=framerate" appears in the remote description, and is "max framerate the remote endpoint can receive". So that's different than local track constraints.

An important distinction we're making is that this is the *pre-degraded* framerate; I'd prefer if this was called out in the definition. Otherwise the text you suggest sounds good for local tracks.

**Comment by henbos** [comment]
How about?

> Only valid for video. It represents the nominal FPS value, pre-degradation. This is the configured framerate for this track attachment to the RTCPeerConnection. For local tracks this is limited by constraints (MediaTrackConstraintSet.frameRate, see [[!GETUSERMEDIA]]) and encoding parameters (RTCRtpEncodingParameters.maxFramerate, see [[!WEBRTC]]). For remote tracks this is the max framerate that the remote endpoint can receive as announced in the remote description ("a=framerate", see [[RFC4566]]). If there is no configured limit this value is undefined.

Should we also include if there are known implementation or device limitations then this may be set for local tracks as well? E.g. camera can't output more than 30 fps or the webrtc implementation doesn't support more than 60 fps. Or should that count as a "degradation" since it wasn't configured by the app?

**Comment by vr000m** [comment]
I believe the intention was: 

> It represents the nominal FPS value before the degradation preference is applied. For local tracks this is the current capture FPS. For the receiver it would be the current decoding framerate.
