### ISSUE TITLE
Stat for audio acceleration/expand rate?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#146]
The non-standardized Chromium getStats contains the following stat:
```
// Fraction of audio samples accelerated (removed) when the jitter buffer size decreases.
ssrc.googAccelerateRate
```
Is this useful? Should this be standardized as `double accelerationRate` in RTCMediaStreamTrackStats?

When it decreases? During what time frame does this rate apply?

**Comment by alvestrand** [comment]
Commentary:
1) this is a rate, which comes under the general ban on rate-valued stats.
2) I'd perhaps go with "samplesInserted", which may be positive or negative. Rate can be computed from that; we shouldn't need a sample counter to divide by, since that's derivable from time + sample rate.

**Comment by henbos** [comment]
@alvestrand WRT "we shouldn't need a sample counter to divide by, since that's derivable from time + sample rate", what sample rate? There are [constraints](https://www.w3.org/TR/mediacapture-streams/#media-track-capabilities) but no stat for that. Packets != samples. And actual sample rate might vary and not be current rate * time.

WRT samplesInsertedByRateAdaption being both positive or negative I don't think it flies to have a single counter, samples can both be removed (googAccelerateRate) or added (googPreemptiveExpandRate) over a period of time but the sum could be zero.

Adding @hlundin. How about?
> **RTCMediaStreamTrackStats._samplesInserted_
> RTCMediaStreamTrackStats._samplesRemoved_**
> The number of samples that have been inserted/removed in order to slow down/speed up audio as the jitter buffer increases/decreases.
> 
> **RTCMediaStreamTrackStats._sampleCount_**
> The number of samples that have been added to the jitter buffer. This count includes both samples that have been inserted (_samplesInserted_) and samples that have been removed (_samplesRemoved_).

Or is "rate adaption" preferred over "jitter buffer"?

So `googAccelerateRate ~= samplesRemoved / sampleCount` and `googPreemptiveExpandRate ~= samplesInserted / sampleCount` if samples were to be counted over the same time period as the goog-rates.

**Comment by vr000m** [comment]
Following up on the discussion:

What is it that we are trying to measure here: 

+ Size of the current or average jitter buffer? 
+ Did the jitter buffer increase or decrease? by how much? 

+ How many samples/packets added and removed from the jitter buffer?

I have a feeling that with the samplesInserted, we'd have more samples than they were generated by the sender?

**Comment by vr000m** [comment]
And another question about inserting and removing sample, when does this happen or under what conditions does it happen?

For example,
+ to bring audio and video in to sync?
+ when the jitterbuffer is going to underflow or overflow? I am assuming the overflow can only happen in the case of a fixed size jitter buffer or at the moment in time it cannot be expanded?
+ or when a low or high watermark in the jitter buffer is met, i.e., the application realises that it needs to slow down or speed up the processing, otherwise this will cause perceptible audio quality issues.

**Comment by vr000m** [comment]
+ number of audible samples concealed (concealment is extrapolated based on speech audio --> audible/speech needs to be defined some where. )
+ number of samples concealed (this concealed includes speech audio, noise generator, comfort sound,  silence, or anything)
+ number of concealment events.

The ratio of samples concealed/number of concealed events may give the idea if there was a large concealment event.

Is it interesting if the concealed packets were recovered. The issue is that the samples lost might affect the decoding of the next few samples (depending if the lost packet impacts the decoder state).

**Comment by henbos** [comment]
Based on offline discussions, information about jitter buffer increase and decreasing should be covered by measurements of the delay of various buffers, see #151. Closing this one.
