### ISSUE TITLE
Stats to keep track of sync between audio and video

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#158]
It would be useful to be able to detect the audio and video of a stream becoming out-of-sync. There should be a current playout timestamp for remote audio and video tracks. They should be monotonically increasing and comparable between tracks from the same remote source.

Shall we add `DOMHighResTimeStamp playoutTimestamp` to `RTCMediaStreamTrackStats`?

**Comment by icydragons** [comment]
SGTM I would suggest lastPlayoutTimestamp to differentiate it from an initial or some other playout timestamp.

WRT the description. I think a little more detail to be able to understand what the clock is. Could you add which clock is used?

For e2e delay we utilize the remoteVideo.currentTime. Could we ensure that we have this in the same location and utilizing the same clock (and on both video and audio)? This can be accomplished by either moving this to the remoteVideo object or add the currentTime to the track stats. This will allow us to track e2e delay by just subtracting as well as a/v sync.

**Comment by henbos** [comment]
What is remoteVideo.currentTime referring to? Is this a time that is synced (ntp?) between local and remote peers?

**Comment by henbos** [comment]
Is this related to ssrc.googCaptureStartNtpTimeMs?

**Comment by icydragons** [comment]
Current calculation for E2E delay is referenced here:
https://github.com/webrtc/samples/pull/27/files

googCaptureStartNtpTimeMs is related, but is something we might not need if we can do this right. Lets see if I can sum up.
----
The googCaptureStartNtpTimeMs is the time that the capture started in the js clock. So lets say it is time 1486405000 when the capture started. 
googCaptureStartNtpTimeMs = 1486405000

Then 10 seconds go by. So the date.Now() inside the js returns: 1486415000. (there is also a step where we use a magic constant to turn js epoch into webrtc epoch, but I'll ignore that here). 
Then remoteVideo.currentTime is the time of the last played out frame in ntp time. So if it took a full second to get there it would be displayed as 9000 (since it's ntp time).

So to get e2e time. You take the js now time "1486415000" subtract the capture start time "1486405000" then subtract the last playout time "9000" to get "1000" or 1 second.

Now to understand the issue with this from a validity perspective (as well as the somewhat convoluted approach) imagine that another second goes by but nothing is getting played out (maybe the renderer is stuck). Then we would have:

You take the js now time "1486416000" subtract the capture start time "1486405000" then subtract the last playout time "9000" to get "2000" or 2 second so it looks like 2 seconds happened, but the E2E delay is still 1sec, it's just adding random time that the current stuff is waiting.
----

So what I want is the ability to use the lastPlayoutTimestamp  - remoteVideo.currentTime and have it be the E2E delay (without having to worry about converting things to and from ntp time in js). This requires that both are reported in the same location atomically though or else there could be a sequence issue. So either both in getStats or both on the object itself (and not sure if there is an analogous for audio, but we want one).

Or, if lastPlayoutTimestamp is equivalent to remoteVideo.currentTimestamp then I want an additional value reported that is the time the video is rendered/audio is played out in ntp timestamp so I can do that calculation. Or an E2E delay stat and the currentTimestamp which would be equivalent.

**Comment by stefanholmer** [comment]
googCaptureStartNtpTimeMs delay is based on an estimate of the time the capture started on the clock of the receiving endpoint, right? If remoteVideo.currentTime would represent the estimated current time of the capturer in the receivering endpoints (local) clock, then I think that might be a good idea.

I'd like the playout timestamp to be currentPlayoutTimestamp, which represents the timestamp which should have been played out at this very moment if there was something to play, and not the timestamp which was last played out. Otherwise we'll have to correct for the time that has passed since the last playout, which will complicate things (and we may need yet another timestamp for that).

**Comment by henbos** [comment]
Should this timestamp continously increasing between frames/audio samples, e.g. not discontinously jumping every time a frame (or audio buffer, how would that work?) arrives, that would complicate things if audio and video jumps by different amount of times or at different points in time.

What happens if you fall behind because there is nothing to play? `currentPlayoutTimestamp` continues to increase but `HTMLMediaElement.currentTime` ("remoteVideo.currentTime") stops?

Is the goal this?
```
// E2E delay
let e2eVideoDelay = videoTrackStats.currentPlayoutTimestamp - remoteVideo.currentTime;
let e2eAudioDelay = audioTrackStats.currentPlayoutTimestamp - remoteAudio.currentTime;
// A/V sync
let audioOffsetFromVideo = e2eVideoDelay - e2eAudioDelay;
```

Which unlike `remoteAudio.currentTime - remoteVideo.currentTime` works even if audio and video did not start sending at exactly the same time from the remote source.

**Comment by henbos** [comment]
If you fall behind, does `HTMLMediaElement.currentTime` "catch up" by playing audio/video faster than 1 second per second?

**Comment by stefanholmer** [comment]
I don't think it makes a lot of sense to do
audioOffsetFromVideo = e2eVideoDelay - e2eAudioDelay;

as it doesn't provide any value and introduces errors. remoteAudio/Video.currentTime are estimates which can be wrong, and audio/videoTrackStats.currentPlayoutTimestamp should already be based on the same clocks and therefore be directly comparable. It doesn't matter when audio or video started 
playing. 

Am I misunderstanding something, or why isn't this enough:

audioOffsetFromVideo = videoTrackStats.currentPlayoutTimestamp - audioTrackStats.currentPlayoutTimestamp

**Comment by henbos** [comment]
It's probably me that is misunderstanding something; I didn't even know about remoteAudio/Video.currentTime until now. If they introduce errors we shouldn't use them.

E2E delay aside, I think `audioOffsetFromVideo = videoTrackStats.currentPlayoutTimestamp - audioTrackStats.currentPlayoutTimestamp` makes a lot of sense.

**Comment by stefanholmer** [comment]
I think it depends on what HTMLMediaElement.currentTime means for webrtc. Is it the current capture time of the source, so that we can actually compute e2e delay based on that and the currentPlayoutTimestamp?

Agree that it doesn't matter for sync offsets.

**Comment by alvestrand** [comment]
Stefan, what would you suggest as base time and units for currentPlayoutTimestamp?
One possible value to expose instead would be timeOfZeroTimestamp - the time, relative to the current time, when the timestamp was zero.
For non-drifting clocks this would be a constant number; for drifting clocks, it would vary (a bit).

**Comment by icydragons** [comment]
It sounds like there are three relevant timestamps (I'm going to use video as this example, but understand that we want the applicable video stats too).

1. lastPlayedFrameCaptureTimestamp - When the frame that was last played out was captured in ntp. 
2. lastPlayedFramePlayoutTimestamp - When the last frame was played out in ntp.
3. hypotheticalCaptureTimeCurrentFramePlayoutTimestamp - The ntp time of when what we would playout was captured, if we could play something out.

hypotheticalVideo - hypotheticalAudio = AV sync
lastPlayedFrameCaptureTimestamp - lastPlayedFramePlayoutTimestamp = E2E delay.

Am I understanding correctly?

**Comment by stefanholmer** [comment]
Harald, you are right, that would be an option. I'm not sure what is easiest to interpret and explain.

Robin, I think you've got it right, but there are other ways to define them too, and I think this is simpler:
1. currentEstimatedCaptureTime - What our estimate of the capturer's clock of this video element is right now (i.e., if a frame was captured now, this is what the timestamp would be).
2. currentlyPlayedCaptureTimestamp - The timestamp which would be played out now if there was something to play out.

e2eVideoDelay = video.currentEstimatedCaptureTime - video.currentlyPlayedCaptureTimestamp
AVSync = audio.currentlyPlayedCaptureTimestamp - video.currentlyPlayedCaptureTimestamp

**Comment by icydragons** [comment]
@stefanholmer That sounds logical, maybe update currentlyPlayedCaptureTimestamp name to not imply that it was played (since it was what would have been played). It does have the issue where if there is a legitimate reason for the other side not to be capturing that hasn't been signaled yet then it will still show up as an increase in E2E delay (because you are measuring the E2E delay of frame n by calculating the estimated delay of frame n+1) rather then calculating the delay of frame n.

Is it expected for video.currentEstimatedCaptureTime - audio.currentEstimatedCaptureTime = 0?

What is the plan for these metrics if a stream is muted? One issue with the current metric is that we can get giant jumps/continual increase when things become muted or unmuted.

**Comment by henbos** [comment]
I would expect `video.currentEstimatedCaptureTime - audio.currentEstimatedCaptureTime = 0` in order for `AVSync` calculation to work. I would not expect it to work between different remote endpoints.

Leaving these stats undefined is an option for muted streams, of course that requires us to have been signaled that it's muted.

How are these timestamps estimated?

**Comment by stefanholmer** [comment]
If we no longer receive frames we could extrapolate both values for a few seconds, and then stop updating them / changing them to N/A. Extrapolating should result in the same E2E delay as before, I think?

**Comment by stefanholmer** [comment]
And yes, in a perfect world I agree that video.currentEstimatedCaptureTime - audio.currentEstimatedCaptureTime = 0, but likely it will often not be. And even if it is 0, that doesn't mean the estimates are correct, but it could perhaps tell us if we shouldn't trust the e2e delay estimate.

**Comment by henbos** [comment]
@stefanholmer @icydragons Trying to piece things together based on previous discussions. I want to come up with a definition. Is this correct and how does this sound?

- _Last known NTP timestamp_ - Video frames and audio samples arrive with RTP timestamps that are periodically mapped to NTP timestamps through messages mapping RTP to NTP. (@vr000m Is this spec'ed behavior or implementation specific?)
- `RTCMediaStreamTrackStats.playoutTime` - This is the estimated playout time, in NTP timestamp, of this track. It is the time of what is currently being played out, or what the time supposedly would be if there was something to be played out. It is extrapolated between video frames and audio samples. It is the _last known NTP timestamp_ + the time elapsed since that video frame or audio sample arrived.
- `RTCMediaStreamTrackStats.estimatedCaptureTime` - This is the estimated current time, in NTP timestamp, of the remote source. This is the _last known NTP timestamp_ + half of the estimated round trip time when that video frame or audio sample arrived + the time elapsed since that video frame or audio sample arrived.

Notes:
- Extrapolating with "time elapsed since..." means we don't have to care about frequency differences between audio and video or do special magic if audio or video packets arrive with different intervals or one/both of them lags.
- `audio.estimatedCaptureTime - video.estimatedCaptureTime` should be roughly zero but could be different because the round trip time estimate could be different for the audio and video streams.
- `e2eVideoDelay = video.currentEstimatedCaptureTime - video.playoutTime`, this is half of the estimated round trip time of the video frame (or eq. for audio sample) that provided the _last known NTP timestamp_.
- `AVSync = audio.playoutTime - video.playoutTime`

**Comment by stefanholmer** [comment]
I don't follow this: "It is extrapolated between video frames and audio samples."

I would have expected something like "The playoutTime is the last played out NTP timestamp extrapolated with the time elapsed since it was played out", or something like that.

**Comment by henbos** [comment]
Yes, that's what I meant, your way of phrasing it is better. +1

**Comment by icydragons** [comment]
It would be interesting to calculate and report video.currentEstimatedCaptureTime - audio.currentEstimatedCaptureTime and compare it to 0 to use as a makeshift "uncertainty" on the metric.

Just to make doubly sure on the extrapolation comment. The audio playoutTime is extrapolated from the last played out audio packet and the video playoutTime is extrapolated from the last played out video packet, right?

That all makes sense to me. Thanks!

**Comment by henbos** [comment]
Are the timestamps per packet or per audio sample / video frame? "Last played out packet" might be a little ambiguous if a packet can partially contain multiple frames? Do we say extrapolated from the last played out audio samples / video frame rather than packet?

**Comment by stefanholmer** [comment]
We shouldn't talk about packets as there can be several packets per frame, and in theory we could even have both audio and video in the same packet. Samples and frames make more sense.

**Comment by henbos** [comment]
See https://github.com/w3c/webrtc-stats/pull/187#pullrequestreview-37254569 for excluding estimatedCaptureTimestamp:

> captureTimestamp removed after offline discussion: The RTCP SR packet containing the NTP timestamp doesn't give us a RTT estimate because the local and remote clocks aren't in sync.
> 
> If the alternative is to use RTT estimates from STUN pings then we're ignoring delays due to encoding and packetization and using an RTT from other packets than the media packets. If this is acceptable in the estimatedCaptureTimestamp this can already be calculated by taking track.estimatedPlayoutTimestamp + iceCandidatePair.currentRoundTripTime / 2 and we don't need a new stat for it that could be slightly misleading due to the difference between media packets and stun pings.

**Comment by haveaguess** [comment]
> I don't think it makes a lot of sense to do
> audioOffsetFromVideo = e2eVideoDelay - e2eAudioDelay;
> 
> as it doesn't provide any value and introduces errors. remoteAudio/Video.currentTime are estimates which can be wrong, and audio/videoTrackStats.currentPlayoutTimestamp should already be based on the same clocks and therefore be directly comparable. It doesn't matter when audio or video started
> playing.
> 
> Am I misunderstanding something, or why isn't this enough:
> 
> audioOffsetFromVideo = videoTrackStats.currentPlayoutTimestamp - audioTrackStats.currentPlayoutTimestamp

Apologies for barging in on this old thread but I tried to do this (to debug lipsync issues Im seeing in Twilio implementation) and the currentPlayoutTimestamp seems to be static and unchanging in my chrome dump, any ideas what I am doing wrong?

**Comment by henbos** [comment]
I don't think we have currentPlayoutTimestamp noawadays?

There's [estimatedPlayoutTimestamp](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-estimatedplayouttimestamp) in chromium.

And [captureTimestamp and senderCaptureTimeOffset](https://w3c.github.io/webrtc-extensions/#rtcrtpcontributingsource-dictionary) where I think captureTimestamp is implemented? Not sure of the status. But that one also depends on RTP header extensions

**Comment by haveaguess** [comment]
Hi Henbos, thanks for your reply. 

Apologies I did actually mean estimatedPlayoutTimestamp.

So in the Chrome dump I'm seeing : 

```
"RTCInboundRTPVideoStream_1182979432-estimatedPlayoutTimestamp": {
"startTime": "2020-12-26T17:39:14.380Z",
"endTime": "2020-12-26T17:40:49.354Z",
"values": "[3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000,3817990000000]"

```

So the timestamp doesn't seem to be changing?

**Comment by henbos** [comment]
Are you doing receive-only? AFAIK it is based on RTCP feedback so you need to make sure RTCP is flowing, which may only be available when you both send and receive. Though I don't know the implementation details on this one

**Comment by haveaguess** [comment]
Thanks again. 

Yep, from the same webrtc dump you can see outbound video stream info:

![image](https://user-images.githubusercontent.com/85821/104967895-62c9c680-59dc-11eb-92d0-0ad713df4475.png)

.. so I would expect it show. I'll take a look and see if I can learn more about what's happening..

**Comment by henbos** [comment]
Alright can you file an issue at https://crbug.com/webrtc and perhaps we can assign it to someone who worked on implementing this stat?
