### ISSUE TITLE
Is keeping stats around a memory problem?

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-stats#235]
This surfaced in a discussion in a webrtc-pc [Issue](https://github.com/w3c/webrtc-pc/issues/1507). Basically the question is whether keeping stats for objects that are no longer in use will cause problems from a memory perspective. Please refer to https://github.com/w3c/webrtc-pc/issues/1507 for more input.

**Comment by jesup** [comment]
> But Dan's point about stats is that we already have another problem about memory use increasing indefinitely. Stats for deleted objects are kept around forever:

>>    The general rule is that stats objects, once created, exist for the lifetime of the PeerConnection that contains them, even when the underlying object they report on is stopped or deleted. This is important in order to report consistently on short-lived objects and to be able to report totals over the lifetime of a PeerConnection.

Unless I'm missing something (possible), the memory usage should be proportional to the objects in a peerconnection.  unless the number of objects grows without bound, we won't have the stats growing without bound.  If you add a new track, there may/will be a new trackstats object as well - but not an infinite number.  Perhaps some of the candidate/transport objects might be proportional to the number of ICE restarts/renegotiations. 

The memory may be in use until the peerconnection itself has gone away. (Note: gone away doesn't mean closed.)

**Comment by taylor-b** [comment]
The number of objects *can* theoretically grow without bound. Suppose I join a persistent group call where participants are regularly leaving and joining, each time using a new SSRC, resulting in a new stream stats object. The list of historical `RTCInboundRtpStreamStats` objects kept around would continue to grow.

**Comment by stefhak** [comment]
@taylor-b I guess the provider of the service would be aware, and could work around (e.g. by having the client close and de-reference the PeerConnection and creating a new one when the number of unused objects grow over a certain threshold)?

**Comment by taylor-b** [comment]
@stefhak I'm sure that's possible; people have gone to such lengths just to work around bugs. I'd also assume that the amount of applications that will run into this problem will be relatively low.

But I wonder if anyone would be opposed to adding a `clearOldStats` method to `RTCPeerConnection`. I can't imagine it being difficult to implement.

**Comment by vr000m** [comment]
My challenge with `clearOldStats` is, there are several third-party libraries polling getStats, any one (app or third-party) calling clearOldStats would mean loss of information for any of those libraries.

**Comment by taylor-b** [comment]
Good point. I guess another approach would be to do something like this:

> When a monitored object is destroyed, a final stats object is produced, carrying the values current at the time of destruction. This object will be returned, with a timestamp reflecting the time of destruction, whenever getStats() is called, **for a minimum of X minutes after the monitored object was destroyed**.

**Comment by vr000m** [comment]
I think destroying after X minutes is okay, and it might work for us,  although AFAICT many apps read stats at the end of the call, they might be caught unawares, if they are not polling periodically. (and their period needs to be shorter than X).

Additionally, maybe throwing an event when an object is destroyed? the app and the third party libs can attach handlers to it and call getStats(), which would mean that apps that do not poll regularly have a chance to collect/snapshot the stats data.

**Comment by taylor-b** [comment]
> AFAICT many apps read stats at the end of the call, they might be caught unawares, if they are not polling periodically

Good point.

> Additionally, maybe throwing an event when an object is destroyed? the app and the third party libs can attach handlers to it and call getStats(), which would mean that apps that do not poll regularly have a chance to collect/snapshot the stats data.

This is starting to sound more complicated than it's worth... Maybe we should table this issue until it turns out to be a real problem for someone.

Also, couldn't an implementation solve this problem by storing stats for deleted objects in a temporary file, and reading from it when `getStats` is called?

**Comment by vr000m** [comment]
> Also, couldn't an implementation solve this problem by storing stats for deleted objects in a temporary file, and reading from it when getStats is called?

I do not see how I would make an application do the above for us.

**Comment by taylor-b** [comment]
> I do not see how I would make an application do the above for us. Wouldn't the event be sufficient for anyone to poll right away and snapshot the data?

Sorry, by "implementation" I meant the webrtc-stats implementation, meaning the browser. I'm saying "if storing historical stats takes too much memory, the browser could mitigate the problem by using hard drive space". That doesn't solve the problem though, just delays it.

I guess I'm just hoping we can avoid making major changes to the stats API to solve this corner case. Having an event for deleted objects would work, but it would be a bit of a burden both for browsers and stats clients, and as far as I know this problem is only theoretical so far.

**Comment by dontcallmedom** [comment]
@jan-ivar reported that Mozilla is not convinced with this approach and will come back with an alternative approach

**Comment by jan-ivar** [comment]
> If you add a new track, there may/will be a new trackstats object as well, but not an infinite number.

Say you `replaceTrack` to flip between front and back camera:

Every time trackA is removed, it leaves a new `detached` version. Every time it's added back, it creates a fresh track stats object (track stats are per attachment). There's no limit to how many times one can do this in JS. It's not so much the memory, rather `getStats` is already slow, and this might slow it down further over time. On ergonomics, this makes stats harder to parse correctly (need to process/filter out `detached` objects correctly to find recent data). See also https://github.com/w3c/webrtc-stats/issues/231.

**Comment by alvestrand** [comment]
A dead stats object is not large (a few hundred bytes? a kbyte?)
Without "objectDeleted" stats objects, I don't see a way to satisfy the other requirements we have - to account accurately for resources used by objects using a polling interface.

There are other ways we could do this (for instance adding an event handler to the PeerConnection that has a stats object fired at it whenever a component object gets detached). I'm not sure if that would be a cleaner design.

(We could even retrofit the old behavior onto such an API by having a default handler that added the stats object, with an objectDeleted marker, to an internal slot called "[[rememberAndReturnTheseStatsObjectsWhenAsked]]" or something like that. But I may be letting my imagination run away with me.)

**Comment by alvestrand** [comment]
@jan-ivar we're waiting for more info here - a convincing case that it is a problem, and a proposed path towards a solution.

**Comment by jan-ivar** [comment]
As I mention in https://github.com/w3c/webrtc-stats/pull/262#issuecomment-350810504 I think we should add `getDeletedStats()` methods instead.

**Comment by alvestrand** [comment]
@jan-ivar that is not a convincing case that there is a problem.
I'd like to have a suggested spec for "getDeletedStats()" too - I can't evaluate a method name.

**Comment by alvestrand** [comment]
Another possible API is to have an event every time a stats object reaches the end of its lifetime, containing the stats at the time of ending / being deleted. That would avoid consuming memory in the case where nobody cares what the stats say (no event listener => no stats produced).

**Comment by lgrahl** [comment]
Isn't this a typical problem that can be resolved with log rotation / a circular buffer? One could imagine an API to set the target size of the log buffer (where of course the browser still has the right to restrict the bounds) with a sane default. The only issues I see is a) how to determine the size of the current log entries, and b) how to make sure the application doesn't poll too slow if it wants to gather all information (maybe raise an event as proposed by @alvestrand).

**Comment by vr000m** [comment]
I missed this bit in the meeting, joined late, what was the decision on this? @alvestrand

**Comment by jan-ivar** [comment]
I covered the problem (the first slide), but ran out of time to present the proposal ([second slide](https://docs.google.com/presentation/d/1o-o5jZBLw3Py1OuenzWDkxDG6NigSmLHvGw5KemKWLw/edit#slide=id.g2d42e878ad_0_17)) that @na-g and I have been working on. PTAL.

It's basically `getDeletedStats()` except we call it `getCompletedStats()` and it can be synchronous, since it's returning a lump of cached data we can keep around and update on the main thread when something is removed.

**Comment by alvestrand** [comment]
Copying my idea from the mailing list:

I've been pondering other options, and came up with one:
<pre>
partial interface RTCPeerConnection {
   attribute EventHandler onstatsobjectended;
}
</pre>
and an event
<pre>
interface RTCStatsEvent : Event {
   readonly attribute RTCStats finalStats;
}
</pre>

The advantage of this is that as long as there's no listener attached,
this produces no overhead that grows over time; when there's a listener
attached, the memory and time overhead is the caller's problem.

It's trivial to shim getCompletedStats on top of this:
<pre>
pc.onstatsobjectended = function(e) {
   pc._completedStats.pushBack(e.finalStats);
}

pc.prototype.getCompletedStats = function() {
   return pc._completedStats;
}
</pre>
The same thing can be added to RTPSender and RTPReceiver, of course.

Thoughts? Is this simpler than getCompletedStats? Are there huge
disadvantages to this approach?

**Comment by vr000m** [comment]
I prefer the event firing rather because it gives the application an indication that something changed. And I think we will need to go and defined in the document when each object becomes obsolete.

**Comment by henbos** [comment]
I think memory or speed wise this is not a problem unless you have a server running for a REALLY long time and people connecting and disconnecting continuously.

I think not keeping old stats around is more of a tidiness problem, it's not nice if you getStats() and half of the things in there are not relevant anymore.

In any case, firing an event when the final version of a stats object is produced due to detachment makes sense, solves any cpu/memory problems (whether real problems or not), and is implementation-wise not harder. Internally stats collection has to occur on a detachment event or callback - whether we do "add to cache" or "fire JavaScript event" is same complexity.

**Comment by jan-ivar** [comment]
@alvestrand I like the event idea.

We might want to bikeshed on the names a bit (final = deleted = completed = ended).

There's also the question (thanks @na-g) of whether the event would contain an `RTCStatsReport` object or an `RTCStats` object (sadly `object` in WebIDL). E.g. is it one event per object:

```js
pc.onfinalstat = e => console.log(e.finalStat.kind == "track");
```
or plural:

```js
pc.onfinalstats = e => console.log([...e.finalStats.values()].some(s => s.kind == "track"));
```


I also filed https://github.com/w3c/webrtc-stats/issues/300 on some timing issues that came up to light while thinking about this.

**Comment by henbos** [comment]
It might be worth firing a full stats report, or a stats report containing everything that was updated.
If you only fire one stats object at a time, you might not have a complete view of stats objects. I.e. maybe the stats object references another stats object that has not been fired yet.

**Comment by alvestrand** [comment]
@henbos if a full report is required at death-time, the handler can call getStats() - I was thinking that if we have many objects (candidate pairs?) dying, the handler shouldn't be FORCED to scan through all the stats every time.

**Comment by jan-ivar** [comment]
I think the goal is only to report precise data you can't get otherwise. My understanding was this mattered to account for absolute final byte counts etc. related to a track that was sent, for accounting. Even though the stats spec doesn't say so explicitly, it'll be necessary to get these exact numbers as part of the *replaceTrack* algorithm, and I wouldn't want to delay *replaceTrack* with a complete stats call.
 
I still vote for returning a `RTCStatsReport` object for consistency, to handle cases where there's more than one stats object deleted from a single action - though it just occurred to me that `"stream"` stats are never removed, except maybe by transceiver.stop() - like all old ice candidates after a SLD with iceRestart.

**Comment by alvestrand** [comment]
I'll write up a PR based on the event-firing idea. It seems to be workable.

**Comment by alvestrand** [comment]
Suggestion to avoid the "references to things that don't exist any more": Let the event have a sequence<RTCStats> as a parameter, so that everything referenced in a stat is either present in getStats() or present in the current event.

**Comment by jan-ivar** [comment]
Btw, would it suffice to return snapshots of `"sender"` stats here? Then we could simplify the spec and remove `"track"` stats as a concept. From @henbos's idea in https://github.com/w3c/webrtc-stats/issues/298#issuecomment-358321601.
