### ISSUE TITLE
packetsLost is unsigned but can be negative according to RFC

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#253]
According to https://tools.ietf.org/html/rfc3550#section-6.4.1 packets lost can be negative if there are duplicate packets received. Our value is "unsigned long".

(What about bustPacketsLost?)

**Comment by vr000m** [comment]
burstPacketsLost are counted as they occur, so they cannot be negative.

**Comment by vr000m** [comment]
should add packetsDuplicated as a result of this.

**Comment by alvestrand** [comment]
packets lost is defined as # of packets received - # of ticks of the RTP sequence number since start-of-call. packets received is actually not carried in an RR, so it has to be calculated from the # of expected packets and the # of packets lost.
Simple solution: Remove "unsigned" from packetsLost and add a note to the definition that it can be negative if more packets are received than sent.
