### ISSUE TITLE
add packetsDuplicated as a result of #253

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-stats#254]
to make sure that the negative losses are due to duplicate packets. 

Should duplicate packet counter increase when:

1. FEC is applied?
2. Retransmission?
3. it is an actual duplicate packet. because a router transmitted a packet twice.

**Comment by vr000m** [comment]
related to #253

**Comment by alvestrand** [comment]
I think it shouldn't increase when packets are reconstructed based on FEC - that's not a packet-level thing.
I think it should be increased when receiving two copies of a packet (two packets with the same RTP sequence number on the same SSRC - I don't think we can keep track of content of packets) - the reason may be because it's retransmitted, or because it's duplicated in the network.
