### ISSUE TITLE
Add estimatedClockSkew

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#258]
Spin-off from #222.
Lots of open questions...

**Comment by alvestrand** [comment]
Please add a few more details. Which clock, and skewed in comparision to what?

**Comment by henbos** [comment]
In order to calculate end to end delay (#222) one has to estimate the difference between timestamps of the local and remote clocks. The idea was that if this was a component we relied on to calculate e2e delay we should expose that component instead of baking that into some other more higher level stat, and the e2e delay would be something you stats consumer calculated instead.

Estimating the skew between the two clocks would be based on SR and RR timestamps and RTT between reports. Or something like that, I don't fully understand the details, @vr000m and @icydragons would have a better idea.

This is when our all day stats hacking meeting ended and we didn't discuss it further.

I'll see if I have time to write some stats PRs tomorrow.

**Comment by icydragons** [comment]
This would be the difference in the NTP timestamps from the sender and receiver, calculated by the receiver. Nominally it would be approximately 1/2 the RTT, but the RTT measurement is calculated to provide an instantaneous value, this could be calculated with the understanding that clocks drift rather then jump and can utilize a smoother algorithm. The current RTT measurements are also only valid for sending clients. This would allow for utilizing other mechanisms for calculating RTT for receiving clients (like https://tools.ietf.org/html/rfc3611#section-4.4) in order to calculate this in more places.

**Comment by alvestrand** [comment]
Suggest moving to the "provisional stats" document.
The art of estimating one way delay (which requires either synchronized clocks or estimating the klock skew) has been an unsolved problem for many years; giving a bad value might be worse than giving no value.

**Comment by alvestrand** [comment]
Will be handled in experimental draft. Closing in this repo for now.
