### ISSUE TITLE
Missing definition of "deleted". When exactly do stats get deleted?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-stats#300]
One problem we ran into looking at `getCompletedStats` - which [using events](https://github.com/w3c/webrtc-stats/issues/235#issuecomment-358316276) might skirt, but nonetheless seems problematic - is the lack of timing guarantees or a definition of completed/deleted.

For instance - even using @alvestrand's [shim](https://github.com/w3c/webrtc-stats/issues/235#issuecomment-358316276) - would the following be guaranteed to work?
```js
let id = sender.track.id;
await sender.replaceTrack(null);
console.log([...pc.getCompletedStats().values()].find(s => s.trackIdentifier == id); // ?
```
Right now there's no guarantee around *when* stats objects end/complete/delete/finalize. Defining it might be hard as well. For instance, @vr000m has mentioned the importance of including every last byte sent wrt a removed track.

Luckily `replaceTrack` is already spec'ed to not resolve until the media switch has been made, but it doesn't talk about that, in order for the stats to be synchronously available in `replaceTrack`'s success callback, we would actually need to gather those stats as part of the replaceTrack algorithm.

This stuff is sort of only implied in the spec so far.

Alternatively, we could offer no such guarantees, and simply say these things happen eventually.

**Comment by jan-ivar** [comment]
The [spec today](https://w3c.github.io/webrtc-stats/#dom-rtcstats-objectdeleted) says *"When a monitored object is destroyed, a final stats object is produced, carrying the values current at the time of destruction"*.

But it's not clear when these objects are destroyed.
 1. Does `replaceTrack` destroy the replaced "track" stats?
 2. Does the destruction of all track stats related to a stream destroy those "stream" stats?
 3. Does `transceiver.stop()` destroy related "sender", "receiver", "track", "inbound-rtp", "outbound-rtp", "remote-inbound-rtp", "remote-outbound-rtp", "codec", and "csrc" stats?
 4. Does iceRestart destroy old "candidate-pair", "local-candidate", "remote-candidate", and "transport" stats?
 5. Does `pc.close()` destroy everything?

**Comment by alvestrand** [comment]
In many cases, the answer will be obvious; in other cases not so much. I think it needs answering for both event-emitting and getCompletedStats cases, and agree that it's not defined clearly now.

1. replaceTrack and removeTrack destroys the binding between the old track and the sender (it's the binding that is tracked by the stat, not the track), which is the end of that "object". I'm not sure the binding can be unbound by any other means - the language about the track stopping describes not sending anything any more, it doesn't say that it gets detached.
2. A stream stat would be destroyed when it's no longer of interest - when it's no longer listed as a stream on any of the incoming or outgoing tracks.
3. transceiver.stop() doesn't destroy anything. In the current API model, transceivers never die.
4. iceRestart should destroy candidate information. For local candidates (which presumably remain stable) I'm not sure if they survive or if the PC gets new candidates with the same value.
5. pc.close() stops all tracks. But the transceivers (and everything related to them) remain in place so that they can be inspected after the stop. I could argue that pc.close() detaches tracks, but I'm not even sure about that.

**Comment by jan-ivar** [comment]
@alvestrand Thanks, that helps a lot. So basically, just *replaceTrack* and *iceRestart* then.

As I mention in https://github.com/w3c/webrtc-stats/issues/300#issue-289452103, what remains then is to try to figure out the timing wrt those APIs (*replaceTrack* and *setLocalDescription* I suppose).

If we're going with events, I think it'd make sense to fire the event right before the *replaceTrack* or SLD calls resolve. Accurately snapshot-ing the number of packets sent that are attributable to the last track and not the new one, I guess already assumes we need to collect stats right in the middle of the in-parallel steps of *replaceTrack*).

**Comment by alvestrand** [comment]
Seems so much easier when we really get down to details :-)

I'm also thinking that pc.close() will by definition freeze all the stats in place, so that "nothing happens after this", including that no stats are emitted as final. Otherwise, there'd be a large number of events fired on pc.close().

**Comment by vr000m** [comment]
PTAL @lennart-csio @karthikbr82 @balazskreith
