### ISSUE TITLE
Add a "panel test" to track implementation status

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#346]
If we're going to advance to PR, we need to know what the implementation status is.
Having a "panel" based on KITE or WPT should give us a list of stats and who implements them.

**Comment by alvestrand** [comment]
Of course, validating that the values make sense is a HUGE benefit!

**Comment by vr000m** [comment]
@karthikbr82 @pallab-gain you folks are in-charge of getting this done for the Stockholm Interim.

**Comment by vr000m** [comment]
webrtc-stats.callstats.io/verify is now available, how do we proceed with this? close the issue?

**Comment by henbos** [comment]
Feedback:
- This is awesome!
- It's sometimes hard to tell which stat corresponds to which box, can you draw a line between stats names and boxes?
- Some stats are listed multiple times, which they absolutely should, e.g. inbound/outbound local/remote rtp stats are different cases and a metric being present in one of these dictionaries doesn't mean it is present in other dictionaries. In addition to the existing view, it would be nice to see what the number of implemented stats and number of total stats are if you discard any stats with duplicate names, and count "implemented" as at least one of the stats with that name being present. It would slightly scew the numbers in our favor but it would give a more accurate view of how much work is being done, since a lot of stats would be added in multiple places if added at all.
- There should be an audio AND video scenario to test, and it should be the default. This gives a more complete picture of which metrics are or are not there.
- Some stats are audio-only or video-only. A video metric being missing in a audio-only call should not count as a stat being missing. Filter out the lists as stat not applicable if it's wrong media type-only.
- Status for other browsers (Safari, Edge) as well.

**Comment by henbos** [comment]
In order to close this issue (unless you want to keep it open as an issue tracker for the above): Please create a PR to link to the panel from the spec.

**Comment by vr000m** [comment]
@karthikbr82 @pallab-gain once we have added safari and edge to the KITE service driving webrtc-stats.callstats.io, create the PR to add a link.

**Comment by alvestrand** [comment]
Target goal may be an .md file in the repo that says what our test plan is.

**Comment by henbos** [comment]
Following the link I see Safari but not Edge? Anyway this is great! I think the only suggestion not addressed was being able to filter out stats with duplicate names but I was just thinking out loud I think that's a suggestion we can ignore.

Shall we make a PR linking to the status page from the README.md?
