### ISSUE TITLE
Should WebRTC be [SecureContext]

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/webrtc-stats#347]
Comment from @ylafon for the W3C TAG on the webrtc-stats CR transition request.

> Note that we are discussing also https://github.com/w3ctag/design-reviews/issues/228 (a spin-off issue from #148), and the TAG would like to ask the WG to mandate the use of SecureContext here as most implementations are doing that anyway. If someone reads the current spec and decide to implement without that restriction, there will be interop issues (ex: getStats() is defined in WebRTC, getUserMedia() from Media Capture as well).

**Comment by alvestrand** [comment]
@ylafon I don't see how [SecureContext] is relevant for the stats document, simply because of how the rules are distributed between it and the webrtc-pc document - this document has no interfaces.
The webrtc-pc document has normative text for the API calls. The stats section (https://w3c.github.io/webrtc-pc/#sec.stats-model) has a "partial interface RTCPeerConnection".

The discussions when reviewing the webrtc-pc document led to a conclusion that it was compliant for a WebRTC implementation to only expose the interfaces in a secure context, and this is what people implement today - but the agreement was to not mandate it at the time.

I can't find a place where this is stated clearly offhand - most relevant I can find is here: https://tools.ietf.org/html/draft-ietf-rtcweb-security-arch-14#section-5.1 - but it doesn't constitute an outright "SecureContext" policy.

I don't think this is an issue for webrtc-pc, for the reasons given in the first para, but it might be reasonable to add it to the list of open issues for webrtc-pc, to be addressed when that spec recycles at CR.

**Comment by alvestrand** [comment]
ping @ylafon

**Comment by alvestrand** [comment]
Thanks - closing issue, please re-raise on webrtc-pc.
