### ISSUE TITLE
Input/output resolution and audio energy

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#353]
The resolution, audio level, etc. values for sender/receiver/track stats are not clear which part of the pipeline they apply to, see discussions at #271.

The sender is really encoder + packetizer: https://photos.app.goo.gl/fyqGKxYMhM247dK47
The same is true for receiver but in reverse order.

We should consider splitting this up sender/receiver into encoder / decoder dictionaries references by the sender/receiver and put the metrics there. Whether we put them there or keep them inside the sender/receiver/track dictionaries, any frame/audio metrics need to have both "inputBlah" and "outputBlah" versions.

**Comment by vr000m** [comment]
"blahInput" and "blahOutput" would be more consistent with for example: packetsSent, packetsReceived, where blah = packets

**Comment by alvestrand** [comment]
If we consider encoders and packetizers as transformative elements, a number of metrics only make sense in one end of the element; for instance, there is no obvious volume in a packet that has audio in it; the volume property (if it exists!) belongs to the stream at the input to the encoder.
The obvious exception is MediaStreamTracks, which have 2 ends of the same form, but with different metrics, because it is a transformative element (scaling, volume sampling, muting).
I'd like to look at only one end for each object, so that we push the input volume up to being a property of the source object (and thus, by definition, becomes the same value for all tracks from the same source).

**Comment by henbos** [comment]
Now that we have "media-source" (pre-encoding), "outbound-rtp" (or sending "track" prior to moving stuff around) and "inbound-rtp" (or receiving "track") versions of these things I think we can close this issue.
- This is true for resolutions on every part of the pipeline (as was available in "goog" stats).
- This is true for the audio volume too of the track; if you want to know the volume prior to the modification of the track's constraints then that is outside the scope.
