### ISSUE TITLE
csrc can be removed and RTCRtpContributingSourceStats can be moved to receiver stats.

### ISSUE THREAD

**Issue by karthikbr82** [w3c/webrtc-stats#371]
webrtc-pc defines RTCRtpContributingSource as part of RTCRtpReceiver.
In order to maintain consistency, we can move the RTCRtpContributingSourceStats to be part of RTCAudioReceiverStats and RTCVideoReceiverStats.

csrc is not in https://www.w3.org/TR/webrtc/#mandatory-to-implement-stats, and as far as i know none of the browsers have implemented this yet.

**Comment by karthikbr82** [comment]
csrc is not in https://www.w3.org/TR/webrtc/#mandatory-to-implement-stats, and as far as i know none of the browsers have implemented this yet.

**Comment by na-g** [comment]
Firefox has implemented RTCRtpContributingSource. It is my understanding that one of the reasons it has its own method is because it is expected to be polled at a higher rate than other stats, and that lumping it in with the others could cause performance issues.

**Comment by jan-ivar** [comment]
> we can move the RTCRtpContributingSourceStats to be part of RTCAudioReceiverStats

Not easily, because it's a one-to-many relationship.

I.e. [receiver.getContributingSources](http://w3c.github.io/webrtc-pc/#dom-rtcrtpreceiver-getcontributingsources) returns a *sequence* of [RTCRtpContributingSource](http://w3c.github.io/webrtc-pc/#idl-def-rtcrtpcontributingsource)s, whereas [RTCRtpContributingSourceStats](https://w3c.github.io/webrtc-stats/#dom-rtcrtpcontributingsourcestats) covers *one* csrc. A one-to-many relationship. E.g. you'd do:
```js
async function collectCsrcStats(receiver)
  const stats = await receiver.getStats();
  return [...stats.values()].filter(({type}) => type == "csrc");
}
```

As @na-g mentions, this works in Firefox (assuming you have a server that emits csrcs).

**Comment by vr000m** [comment]
@karthikbr82 WDYT, close the issue?
