### ISSUE TITLE
Is exposing a remote peer IP address through RTCIceCandidateStats.address a privacy issue

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-stats#375]
In the case of a peer reflexive remote candidate, one peer might disclose the IP address of the other peer that made sure to not disclose this IP address to the web site.
See also https://github.com/youennf/mdns-ice-candidates/issues/3

**Comment by youennf** [comment]
Sure

**Comment by youennf** [comment]
The proposal would be something like:
A RTCICeCandidateStats dictionary should have no address member if its candidateType member is "prflx"

**Comment by juberti** [comment]
We may want to scope this only to cases where the peer did not want the address to be disclosed (e.g, mDNS), assuming this is technically possible.

**Comment by youennf** [comment]
Is there value in exposing those IP addresses in WebRTC stats. From what I heard in https://github.com/w3c/webrtc-stats/issues/374, value might be low (but maybe I am wrong...).

Knowing the value, we should weight it against potential countermeasures.

As to whether a peer wants to disclose its addresses, this is done by providing or not its candidates to the other peer. I do not think we should tie this to mdns, this applies to regular host candidates as well.
IIANM, by definition, prflx means that the STUN sender has not disclosed its IP address.

**Comment by juberti** [comment]
It's definitely useful for call debugging, i.e. what was the media path for this call? What quality level were previous calls on this same media path?

prflx doesn't mean that the STUN sender hasn't disclosed its IP. It can happen even when the STUN sender disclosed its IP because its NAT behavior included endpoint-dependent mapping.

e.g.

local addr is 192.162.1.2 (host)
STUN addr is 1.2.3.4:5000 (srflx)
STUN checks to remote peer come from 1.2.3.4:5001
1.2.3.4:5001 is reported as a prflx candidate, despite the fact that 1.2.3.4 has already been communicated in signaling

**Comment by youennf** [comment]
As per TPAC discussion, the idea is to not expose such IP addresses until the browser knows that they were exposed through other means (being added as remote ICE candidate).
I will prepare a PR for that.

**Comment by youennf** [comment]
Filed PR https://github.com/w3c/webrtc-stats/pull/381

**Comment by youennf** [comment]
In terms of testing, we might be able to do a WPT test by doing:
- Create two PC
- Have one send all candidates and the other none
- Verify that stats do not leak.

This would be more convincing with two different endpoints though. wdyt?

**Comment by henbos** [comment]
Correct me if I'm wrong @youennf , but this was fixed in #381 ? Closing
