### ISSUE TITLE
audioLevel can be removed from "track"|"receiver"|"sender" stats

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-stats#391]
From https://bugs.chromium.org/p/chromium/issues/detail?id=736403#c10
> Given the long time this didn't get any priority... what is the usecase for audioLevel? Could this be removed from the spec? For long-term measurements it useless since it instant (so totalAudioEnergy would be better ... ).
For getting the value, there is now the getSynchronizationSources API.

if I have the history right, the [getSynchronizationSources()](http://w3c.github.io/webrtc-pc/#dom-rtcrtpreceiver-getsynchronizationsources) got added to the spec to solve the `audioLevel` "track" stat being impractical to poll in real-time. So why don't we remove `audioLevel`?

**Comment by jan-ivar** [comment]
The same probably applies to [RTCRtpContributingSourceStats](https://w3c.github.io/webrtc-stats/#dom-rtcrtpcontributingsourcestats).audioLevel (maybe the whole dictionary?)

**Comment by fippo** [comment]
removing it will prevent people from attempting to poll this value at a high frequency

**Comment by henbos** [comment]
Preventing people to poll getStats() at high frequency for the sake of audio level would be a good thing, but note that getSynchronizationSources()[i].audioLevel is only present on RTCRtpReceiver. There is no such thing as is on the RTCRtpSender - should it? I think so, it's only exposing things that we're already sending in the RTP packets anyway. I filed https://github.com/w3c/webrtc-pc/issues/2103

**Comment by vr000m** [comment]
Related to #402

**Comment by henbos** [comment]
Also related to #449. What's currently broken in Chrome is the sender-side audioLevel (the receiver-side audioLevel works fine). As long as audioLevel works in legacy stats but not standard stats people have a reason not to switch. The [bug in question](https://bugs.chromium.org/p/chromium/issues/detail?id=736403) is currently starred by 39 people.

**Comment by henbos** [comment]
We've said in the past "why don't people just use WebAudio" but people seem reluctant to do so, I want to implement this to unblock migration.

Tangent: With regards to people polling getStats() to the point of getting bad performance, I wonder if perhaps we should increase the cache time of getStats().

**Comment by vr000m** [comment]
I believe 'cache time of getStats()' is UA specific?

**Comment by henbos** [comment]
> I believe 'cache time of getStats()' is UA specific?

It is, I'm not suggesting we standardize the cache time, but the thought occurred to me and I'm not sure we ever considered doing that.

**Comment by henbos** [comment]
Some things have been moved around recently, update:
We have totalAudioEnergy for the send-side on "media-source" and on the receive-side on "inbound-rtp" (or receiving "track" stats on obsolete implementations like Chrome). Same for audioLevel, which is "recent audio energy".

We can't rely on getSynchronizationSources() for send-side levels because this API only exists on the RTCRtpReceiver. If we have one of them I think we should have both. Pragmatically, if this doesn't exist here, then people would use legacy goog-stats...

I suggest closing this issue, but an argument could be made for moving them to the obsolete section.

**Comment by henbos** [comment]
This was not discussed at TPAC (the [slide](https://docs.google.com/presentation/d/1Xprz0ElNTUWRDdX6kyp11cZ4ItTvUFUmzoXsKZdXxuU/edit#slide=id.g60354ba5f0_6_136) was skipped).

I propose we close this issue, because we have totalAudioEnergy already. But @jan-ivar do you think audioLevel should be made obsolete because a) it's an instantaneous value, and/or b) it's under-specified? I'm happy to make a PR to move it to the obsolete section, but note that this would not include totalAudioEnergy, which is available for media-source [here](https://w3c.github.io/webrtc-stats/#dom-rtcaudiosourcestats-totalaudioenergy) (send-side) and inbound-rtp [here](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalaudioenergy) (receive-side).

I don't think Chrome would unship it any time soon considering existing usage but it's not needed due to totalAudioEnergy.
