### ISSUE TITLE
Remove RTC[Audio/Video][Sender/Receiver]Stats.remoteSource

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#399]
This information is already available based on dictionary type ("sender" means not remote, "receiver" means remote). It is still needed for ye olde "track" stats though.

**Comment by henbos** [comment]
Move to deprecated

**Comment by jan-ivar** [comment]
I agree with this. Removal also solves the ambiguity of its language: *"True if the source is remote, for instance if it is sourced from another host via an RTCPeerConnection"*

In the [forwarding case](https://webrtc.github.io/samples/src/content/peerconnection/multiple-relay/), where a track from one peer connection is feed into another, this would return `true`, confusing code relying on `remoteSource` to deduce whether it is sending or receiving.

> It is still needed for ye olde "track" stats though.

`"track"` stats in the spec are never remote.

Since I'm doing an audit of mandatory stats, I've taken the liberty of providing a PR. @henbos PTAL.

**Comment by vr000m** [comment]
For an application layer multicast, each node in the tree is forwarding media from one hop-to-another. In this case, a peerconnection will take the output from one peerconnection and attach it to the other peerconnection. 

In this case, we would like to keep the `remoteSource`.

**Comment by henbos** [comment]
I don't understand what multicast or piping peer connections have to do with remoteSource. It should have no relevance? Can you explain what you would expect to happen?

**Comment by vr000m** [comment]
I dont see an issue with remoteSource as defined: "True if the source is remote, for instance if it is sourced from another host via an RTCPeerConnection. False otherwise."

**Comment by vr000m** [comment]
https://github.com/w3c/webrtc-stats/pull/148
