### ISSUE TITLE
Add stats for accelerating/decelarating playout speed

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#407]
The concealedSamples counters only cover samples inserted to conceal packet loss/packets arriving late. These samples are produced when we don't have the necessary non-concealed samples in the buffer.

However, samples may be inserted or removed for other reasons when we do have samples in the buffer. Adding or removing samples for these other reasons can affect quality and we should have metrics for this.

- deceleratedSamples: The total number of samples inserted in order to decelerate playout speed. This can happen to prevent the jitter buffer from becoming empty.
- acceleratedSamples: The total number of samples discarded in order to accelerate playout speed. This can happen to prevent the jitter buffer from becoming full.

If these metrics were added, people relying on Chrome's non-standard googPreemptiveExpandRate and googAccelerateRate could switch to these standard ones. These goog-stats have been rated highly important, so it is very important that we have something to replace them to unblock migration of existing products.

**Comment by vr000m** [comment]
JitterBuffer are proprietary and the methodologies to mitigate these issues are also proprietary. However, I do agree that we should be able to measure jitterbuffer metrics, and there should be metrics for both audio and video:

+ Underflows -- there should be a metric that measures underflow, when the JB is empty. Adding concealment packets because the jitterbuffer is empty should still be counted in the underflow metric. The total number of samples added during those periods and the counter for underflowCounts should give an average.  Similarly, framesDiscarded and underflowCounts should give the corresponding metric for video.

+ Overflow -- there should be a similar metric for overflows as for underflows.

Now accelerated and decelerated samples -- we are changing the playback rate, right? should there not be metrics of how quick this was? how would we measure that?

**Comment by jan-ivar** [comment]
> However, samples may be inserted or removed for other reasons when we do have samples in the buffer

@henbos Can you elaborate on the "other reasons"? Glad to hear these may help aid convergence, just making sure we understand the use case, so we describe it in the spec correctly.

**Comment by henbos** [comment]
@jan-ivar In the latest version of [the PR](https://github.com/w3c/webrtc-stats/pull/408) we are defining these as the difference between number of samples received and number of samples played out due to slowing down or speeding up playout. For example, an implementation may achieve speedup by removing every X samples, and removedSamplesForAcceleration would increase by X. Another implementation may analyze the samples that are in buffer and use some implementation-specific magic to combine these samples, resulting in a playout of X samples less than was received, and removedSamplesForAcceleration would increase by X. In any case these are differences that have to do with acceleration (or deceleration). It does not cover samples removed for "any" reason, i.e. if the jitter buffer is flushed, this does not increment removedSamplesForAcceleration because that is not an acceleration that is a flush. Is the current definition clear?
