### ISSUE TITLE
Clarify qualityLimitationReason when limited by multiple reasons

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#440]
qualityLimitationReason can be "cpu" or "bandwidth", not both. We should clarify what to do in this case, such as to prioritize "bandwidth" over "cpu".

**Comment by vr000m** [comment]
One will typically happen before the other or over-ride the other. 

For example quality is first limited by CPU and then further limited by bandwidth (it is bandwidth) or quality is limited by CPU and bandwidth does not constrain the number further (CPU).

**Comment by henbos** [comment]
If you are limited in either case, that makes you less limited in the other case, these cannot be measured independently because any limitation changes the resource load of both resources (CPU and bandwidth). It really is not clear whether an implementation should say "cpu" or "bandwidth" in a given scenario that is some amount of limited in both. I think the order of detection ("first CPU was detected, then bandwidth was detected") adds complexity and assumptions without necessarily increasing interop or testability.

What Chrome does is that if both limitations have been detected (in any order) is it always says "bandwidth" (see discussion [here](https://webrtc-review.googlesource.com/c/src/+/138825/1/video/send_statistics_proxy.cc#1076)). I propose the spec should reflect the only implementation that has been shipped for this metric, as does @alvestrand:

> We discussed "cpu-and-bandwidth" when we added the stat, but a) it leads to combinatorial explosion if we add more limitation reasons, and b) if you reduce quality because of bandwidth limitations, CPU usage is also likely to drop, but you can't tell that the dropped CPU usage is because of the bandwidth limitation or because you'd also like to do CPU throttling. So I think prioritizing bandwidth is right, and the spec should say so.

**Comment by vr000m** [comment]
I am assuming that issue stems from the fact that at the output of the encoder, where the quality is measured, it is not clear what was the expectation from the bandwidth estimator nor that it was further limited by "cpu"?

In my mental model, the target quality (the input to the encoder) is set by the bandwidth estimator, and if the output comes out lower than the target (it is either due to "cpu" or something else).

To expand on the above, my interpretation of the usecase for quality limitation was:
1. target quality for the encoder is always set by bandwidth estimator, because it is component that is actively trying to modulate the video bitrate to fit the estimated capacity. Now if the bandwidth estimate is varying, and if the quality produced by the encoder is limited because of the bandwidth estimator, it is reasonable expectation to set it as "bandwidth". I can imagine at the beginning of the call, it has no estimate, the quality would default to a preset, if a bad preset is used, it would fall in to "other"?

2. output quality turns out to be lower than the target quality set by the bandwidth estimator, I would imagine this is either because of "cpu" limitation or input picture does not have enough fidelity to create high quality ("other").

**Comment by henbos** [comment]
> To expand on the above, my interpretation of the usecase for quality limitation was

I must admit that I don't know how the quality reason is determined, but what you write sounds very reasonable. I think there are problems in how these reasons are related though.

Any given point in time you might limit limit quality because of a reason. Assuming there are multiple reasons at this point in time, which reason is reported first would be implementation-specific, so straight away we might have a problem. But let's say we're only limited because of X.

OK so now you are limited because of X, and time passes. Things change, but you are still in a lower resolution. Are you also limited because of Y? Would you know without ramping up the resolution and seeing if you get problems? For bandwidth, maybe, can it estimate higher rates than current throughput? For cpu, I would assume we don't know unless we try and fail? But I don't actually know how these things are estimated.

Let's assume you are also limited by Y, you just have not experienced Y lowering the resolution because you're already lowered. OK. So which reason is the most limiting reason; X or Y? Could you know? Perhaps whether X or Y was the first reported reason earlier was a coin flip, and any attempt to test this would be flaky. Perhaps not, I guess it would depend on the implementation. The point is, X and Y are related, and I think we're getting into implementation-specific territory.

Options:
1. We define the reason to be the most limited factor, but because of the problems in determining this, we define this as an implementation-specific _best effort_.
2. We prioritize "bandwidth" over "cpu", which is Chrome's best effort.

Maybe even 2) is problematic. If you're "cpu" limited, would you be able to detect that you are also "bandwidth" limited? I'm not sure, but I'm hoping the answer is "yes" because of the bandwidth estimator.

**Comment by henbos** [comment]
TPAC decision: No consensus. Figure this out here or in a PR.

**Comment by henbos** [comment]
I'll suggest something like "If the implementation is able to estimate what the most limited reason is that is what it reports, otherwise it should prefer to report bandwidth over cpu."
