### ISSUE TITLE
Detecting Video Playback glitches

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#443]
Chrome's legacy stats has "googInterframeDelayMax".
This can help detect if any time during the call there was a large delay between frames such as a glitch.

The standard API has stats useful for detecting long freezes, such as by looking at framesPerSecond, framesReceived and lastPacketReceivedTimestamp.

But if a minor freeze/glitch occurs of say 100 ms this might not be noticed by an application that polls getStats() every one or several seconds.

Using framesReceived on a per-second basis, a 100 ms loss of frames would certainly be noticeable, but it would look the same as if the frame rate was slightly reduced; not as bad for the user experience as a glitch.

Should we add a new metric for this? Can it be done without a "max" metric? (Problem with "max" is it says nothing about recent stuff, it speaks of the entire history of the call.)

**Comment by ilyanikolaevskiy** [comment]
The old metric returns the max for 1 second window. It's designed, so that application polling getStats every second would notice any glitches. It can be alternatively changed to be a maximum inter-frame delay since the last GetStats call.

No other aggregation than max can help to identify such glitches: after a 100ms glitch, next frames would be decoded and sent for render almost immediately. So average inter-frame delay for the second with the glitch would stay the same. Fps wouldn't be affected either.

**Comment by henbos** [comment]
Returning something for a recent interval has precedence in another WebRTC API: getSynchronizationSources() and getContributingSources() (in that case returning information related to recent RTP packets for the last 10 s).

"Since last call to getStats()" is nice in many ways but something we have purposefully avoided for all other metrics because it breaks use cases where there are multiple stats consumers.

A third option is bucket counters with record&lt;&gt; to count the number of times delays of various magnitudes occurs.

**Comment by ilyanikolaevskiy** [comment]
Yes, I agree that the second option is not so good.

Regarding the third option, it might be even just a list of interframe delays, since (usually) there's no so many frames per second. The bucket is tricky, since it's not clear what should the rages be. It should also depend on frame-rate.

**Comment by vr000m** [comment]
bursts metrics are the best way to do something like this.

Define a minimum time threshold that would invoke the counter, total duration metric that would count up all freeze durations, and a max frozen duration which would be the maximum observed freeze duration.

typically, I would do something like: 
```
non_max_duration = total_freeze_duration - max_frozen_duration
avg_non_max = non_max_duration/freeze_count
// if avg_non_max is much lower to max_frozen, then max_frozen was an anomaly
```

**Comment by ilyanikolaevskiy** [comment]
@vr000m, This could help to detect glitches but this metric must be tuned first. It also should depend on a frame-rate, because 200ms inter-frame delay for 5 fps video is great, yet of 30fps it's terrible. Then the problem arises - the actual frame-rate may be anything other than configured value, because e.g. a capturer is being too slow. So now the threshold value should depend on the measured frame-rate.

I think just a maximum inter-frame delay or a list of all delays (<60 of values) is much easier to interpret. The user of the metric may then compute whatever they may need.

Also, non-filtered value is useful to see if the video is indeed the intended 30fps or not.

**Comment by henbos** [comment]
TPAC decision: Add sumInterFrameDelaySquared with a note that this can be used to calculate the standard deviation
