### ISSUE TITLE
New Respec issues

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-stats#468]
Failed to parse WebIDL: Bodyless dictionary. at: 1.
Details
Failed to parse WebIDL: Bodyless dictionary. at: 1.
Details
The term "boolean" is defined in infra, webidl in multiple ways, so it's ambiguous. See how to cite to resolve the error at: 1, 2.
The term "boolean" is defined in infra, webidl in multiple ways, so it's ambiguous. See how to cite to resolve the error at: 1.
The term "boolean" is defined in infra, webidl in multiple ways, so it's ambiguous. See how to cite to resolve the error at: 1, 2.
The term "record" is defined in html, webidl in multiple ways, so it's ambiguous. See how to cite to resolve the error at: 1, 2, 3.

**Comment by henbos** [comment]
I merged the other PR and get this on tip-of-tree, oops:

😱 ReSpec error: Multiple `<dfn>`s for `framesDecoded` in `RTCInboundRtpStreamStats`
😱 ReSpec error: Multiple `<dfn>`s for `framesDecoded` in `RTCInboundRtpStreamStats`
😱 ReSpec error: Failed to parse WebIDL: Bodyless dictionary. at: [1](#respec-offender-bodyless-dictionary).

<details><pre>Syntax error at line 1 in 40, since `partial dictionary RTCAudioSenderStats`:
partial dictionary RTCAudioSenderStats : RTCAudioHandlerStats {
                                       ^</pre></details>
😱 ReSpec error: Failed to parse WebIDL: Bodyless dictionary. [object HTMLPreElement]
😱 ReSpec error: Failed to parse WebIDL: Bodyless dictionary. at: [1](#respec-offender-bodyless-dictionary-0).

<details><pre>Syntax error at line 1 in 41, since `partial dictionary RTCAudioReceiverStats`:
partial dictionary RTCAudioReceiverStats : RTCAudioHandlerStats {
                                         ^</pre></details>
😱 ReSpec error: Failed to parse WebIDL: Bodyless dictionary. [object HTMLPreElement]
😱 ReSpec error: Failed to parse WebIDL: Bodyless dictionary. at: [1](#respec-offender-bodyless-dictionary-1).

<details><pre>Syntax error at line 1 in 42, since `partial dictionary RTCVideoHandlerStats`:
partial dictionary RTCVideoHandlerStats : RTCMediaHandlerStats {
                                        ^</pre></details>
😱 ReSpec error: Failed to parse WebIDL: Bodyless dictionary. [object HTMLPreElement]

**Comment by henbos** [comment]
I merged the above PR, Travis now appears to pass: https://travis-ci.com/w3c/webrtc-stats/builds/123220395

So I guess we can close this issue? Thought I don't recognize the errors you describe above about boolean and record - is this still an issue?

**Comment by henbos** [comment]
Looks like it's working locally as well, I'm closing this one, feel free to re-open
