### ISSUE TITLE
Add metric for ICE reroutes

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#474]
High number of ICE restarts positively correlate with bad network/quality, and would be a useful metric to have.

An ICE reroute is when the ICE candidate pair changes. I propose adding:

> unsigned long RTCTransportStats.selectedCandidatePairChanges:
> The number of times that the selected candidate pair of this transport has changed.

**Comment by alvestrand** [comment]
Nit: I think it positively correlates with bad network quality.... at least I hope so.
Since ICE restarts are an application function, the number of restarts depends on application logic, so it's not clear that it makes sense to count them.

Changes of the selected candidate pair (which can only happen under continuous renomination, which is an ICE extension) absolutely make sense to count.

**Comment by jonasoreland** [comment]
Correct.
s/ICE restarts/ICE reroutes/ in text above.
But the error is only in the issue...
