### ISSUE TITLE
RTCVideoSourceStats.framesPerSecond should be a double

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-stats#540]
All the fields `framesPerSecond` as defined as `double` except in `RTCVideoSourceStats` where it is defined as an unsigned long.

**Comment by alvestrand** [comment]
Wonder if we did this right. The definitional text for these entries says that it's a count, not a calculation ("number of frames ... in the last second").
Implementation has it somewhat approximate, though, so double may be more fitting.

Suggest to leave it as is, but wanted to record the doubt.

**Comment by vr000m** [comment]
I think the intention of the metric to return the latest Or current FPS for frames received in the last second. 

Much like round trip time, which also returns the latest RTT measurements. 

So this is invariant to how often you call getStats, it would always return the current value. 

Otherwise, I'd recommend that we use  the delta of framesSent and/or framesDecoded between two getStats API calls to calculate that interval's FPS.
