### ISSUE TITLE
Define reception time for jitterBufferDelay stat

### ISSUE THREAD

**Issue by murillo128** [w3c/webrtc-stats#549]
Currently the `jitterBufferDelay` stat is defined as:
```
It is the sum of the time, in seconds, each audio sample or video frame takes from the time 
it is received and to the time it exits the jitter buffer.
```
When tried to land a patch for libwebrtc to correct the current implementation (https://webrtc-review.googlesource.com/c/src/+/168042), it has been risen the concern that it is not clear what the reception time really mean:

1. The reception time of the RTP packet as close to the network layer as possible
2. The reception time of the RTP packet by the jitter buffer code
3. The time when the audio samples have been already decoded and ready to be passed to the jitter buffer internal queues

In case of (2) or (3), we would need a new stat defined for (1)  (playoutDelay?)

**Comment by henbos** [comment]
@alvestrand @ivocreusen Do you have an opinion?

I think the original wording of the spec was supposed to describe the implementation, or something close enough to be standardizable, but I don't know the details well enough to have an authority here.

Questions:
- What does the current implementation measure?
- What would be the most useful thing to measure?

I think we can either update the implementation or update the spec. Or update the spec to match the implementation and then add another metric to give us the remaining information, if the current implementation is still useful on its own.

**Comment by murillo128** [comment]
Currently, libwebrtc implementation sets the reception time as when the rtp packet is inserted in NetEq, my patch uses RTP network reception time instead.

As an app developer, I don't really care about how much delay does the NetEq introduce but what is the total playout delay since the rtp packet was received from the network. 

In normal conditions, the processing time before NetEq would be minimum, but I have seen it going up to several 10ms in cases of high cpu loads.

**Comment by henbos** [comment]
Taking a closer look at the spec definition and discussing with libwebrtc colleagues:

I think the intent of the spec is that it is the time spent in the jitter buffer, i.e. the time it is inserted until the time it is exited. I think the spec should be clarified to say "time it enters" rather than "is received". This is well defined enough that different webrtc implementations could be confident that they're measuring the same part of the pipeline, and simple enough to implement.

As I understand things, there isn't additional _buffering_ going on prior to the jitter buffer other than perhaps network card and OS level buffering before the packet reaches webrtc, which we don't have a metric for, probably don't want to have a metric for, and isn't what your CL attempts to calculate anyway.

I think what your CL is trying to catch is some implementation-specific stuttering... the packet arrives and there's a thread jump before it is put in the jitter buffer. I don't think jitterBufferDelay should include such a thing. A different implementation might stutter in a different way (maybe it is slow at reading packets from the OS buffer), and it wouldn't be testable which thing is measured.

jitterBufferDelay should not be a proxy for measuring CPU glitches or how slow the pipeline is at reading packets on the network thread.

While more metrics that tries to cover as much ground as possible is nice to have I don't think this particular problem should be solved in jitterBufferDelay because it makes the stat definition and implementation of the metric more complicated.

And there are other delays too (like network RTT). What is it we really want to measure? For end-to-end delay metrics there is this (currently unresolved) issue: https://github.com/w3c/webrtc-stats/issues/537. This problem might gain more traction when we have RTP header extensions for the capture time.

**Comment by henbos** [comment]
@ivocreusen Thoughts?

**Comment by henbos** [comment]
Proposal:
- Clarify jitterBufferDelay as "time it enters" the buffer.
- Measuring additional delays should be addressed as separate metrics or, if this is only a CPU glitch measure, then perhaps not at all.

**Comment by murillo128** [comment]
I strongly disagree with this, if this is the case, the jitterBufferDelay is useless if it just covers the time it is spent on the NetEq code which is only relevant for your implementation.

As a developer I need to know what is the delay between the packet is received by the network until it is ready to be played.

**Comment by ivocreusen** [comment]
I think the time a packet is received is hard to pinpoint exactly. Packets go through many layers before reaching WebRTC code, such as the network card, the OS, various Chrome layers. Each of these layers can add some delay (especially during high-CPU load), so starting the timer when the packet reaches WebRTC code is a bit arbitrary. 

Ideally there should be very little delay between a packet reaching WebRTC and reaching NetEq, and in the vast majority of cases this is true. If there is high delay in this part of the code, that should be considered to be a bug in the implementation.

The name "jitterBufferDelay" suggests that it is the delay that is added by the jitter buffer, and this delay is different from other accidental sources of delay, because the implementation actively chooses to add it. There is also delay after audio leaves the jitter buffer, for example in Chrome layers, the audio driver and the audio hardware, and we also do not include these delays in this metric.

**Comment by alvestrand** [comment]
If the purpose is to measure end-to-end delay, then jitter buffer delay is indeed useless.
In the common transmission chain of server host -> outgoing router -> ISP router* -> home NAT -> home AP -> PC Wifi card -> PC network buffer -> Chrome network process -> Chrome renderer process -> jitter buffer, I don't see a point that is easily reachable that is a reasonable definition for "packet arrival" - the most reasonable time would be the time at which the checksum is verified in the Wifi card for the incoming packet, but there isn't an easy way to get hold of that time.

In WebRTC, I think we should be aiming for guesstimating end-to-end delay, and quantizing delays that are fully within the WebRTC model of things.

**Comment by henbos** [comment]
@murillo128, if you had an end-to-end delay estimate in the stats, would you still think jitterBufferDelay should encompass more of the "packet arrival" part of the pipeline and not just the jitter buffer?

**Comment by murillo128** [comment]
Regarding reception time, it should calculated in the same "place/layer" as the reception time used for  the DSLR of the RTCP SR/RR. DSLR is used for calculating the rtt,  so it makes sense to consider anything before that layer as "network transmission time". Obviously, the closest to the hardware as possible, but this should not be a specific issue for calculating stats (it affects also transport wide cc feedback messages).

I am not against having a jitter buffer only stat, the more stats the better. But I think that having a stat that calculates the time between the reception time and the the play time (as accurately as possible) is interesting for both app developers (which care more about that than the jitter buffer delay).

Would it make sense to modify the `jitterBufferDelay` to account jitter only processing time (and only for audio, so it could even be moved into  `RTCAudioReceiverStats` ) and a new stat called `playoutDelay` that takes into account the time since reception until it is ready for playback (as close to the display layer as possible). The `playoutDelay` stat would make sense for both audio and video.

Also, this would make sense as the `playoutDelayHint` attribute is aiming to provide the hint for play out delay, and not just the jitter buffer delay.

Regarding the e2e delay estimate, I will answer in the corresponding issue.

**Comment by alvestrand** [comment]
having a stat that corresponds to https://w3c.github.io/webrtc-extensions/#dom-rtcrtpreceiver-playoutdelay may be reasonable.

**Comment by vr000m** [comment]
My take on this is the time it takes from the RTP layer getting the packet and the media takes to render the packet. 

"The reception time of the RTP packet by the jitter buffer code".

**Comment by henbos** [comment]
Proposal:
- Keep jitterBufferDelay as-is but clarify that it is time of entrance when we start counting.
- Add a new metric for playoutDelay, encompassing time from reception (e.g. reading the UDP packet) until time of playout (to be discussed: when is "playout"?)

**Comment by murillo128** [comment]
Note that, at least in libwebrtc these two are not equivalent:
 
> the time it takes from the RTP layer getting the packet and the media takes to render the packet.

> the time it is received by the jitter buffer to the time it exits the jitter buffer

Anyway, I am fine with the later if we have a different stat to try to cover the complete processing time since reception to playback.

**Comment by murillo128** [comment]
how about video? https://github.com/w3c/webrtc-stats/issues/441

should we say that this is an audio only stat?

**Comment by vr000m** [comment]
@murillo128 does #568 resolve your issue? we might consider changing this metric to decoding delay instead, that might seem more appropriate.

**Comment by murillo128** [comment]
@vr000m yes that would fix my issue,. Not sure if decoding delay is the best name either, as it could be seen that it is only the time spent in decoding (no jitter or after decoding buffers). Maybe just `totalDelay`?
