### ISSUE TITLE
ActiveIceCandidatePairStats.bytesReceived (even when no tracks were subscribed to)

### ISSUE THREAD

**Issue by makarandp0** [w3c/webrtc-stats#613]
This is a mostly a noob question - I see that `ActiveIceCandidatePairStats.bytesSent` are increasing on a PC that is not publishing any tracks, similarly `bytesReceived` are increasing on the PC that is not subscribed to any tracks. 

See:
https://codepen.io/makarand-patwardhan/pen/WNZaBKN
which creates a loopback connection and monitors stats.

What goes into these bytesSent/bytesReceived besides media bytes? It wasn't very clear to me looking at the [specs](https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatepairstats-bytessent).
Can somebody please point me to where to look for more information? Thanks!

**Comment by fippo** [comment]
You get ten experience points for asking a great question. Check your level.

https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatepairstats-bytessent
is defined as *not* including STUN checks which would be in the order of ~100 per second.

RTCP is the obvious culprit. The fiddle makes it hard to see though since there is an active track drowning everything else.
Did you check with a stopped track? Wireshark should give you a good number (including SRTCP overhead)

**Comment by makarandp0** [comment]
Thanks @fippo, I added a "stop track" button and as you said we still see bytes sent and received even after track was stopped. So is it safe to say that even when a PC is not receiving any track, it would see non-zero `bytesReceived`?

**Comment by fippo** [comment]
That looks like RTCP sender/receiver reports.
They'll continue to be sent and received until you stop the transceiver I think.

**Comment by makarandp0** [comment]
Thanks for the info, I will close this issue now.
