### ISSUE TITLE
add stats about Detect CPU/GPU overuse on receiving(decoding) side

### ISSUE THREAD

**Issue by byterldp** [w3c/webrtc-stats#645]
in a  multiparty call, where decoding side has to decode N videos , the stream sender may send simulcast stream with diff resolution ,   
the SFU (middle box send side)  can detect receiving side bandwith and auto switch stream resolution for receiving side,  some times, the receivinng side may have good network connection but with bad cpu performance, it takes a long time to decode and render the video, in such case, there are two way to make decoding side switch to receive low resolution video.
1. the decoding side detect cpu overload,and switch receive video resolution from heigh to low manualy 
2. the decoding side detect cpu overload and report its performance state to SFU , sfu auto switch sending stream from heigh resolution to low.
  
both those method need decoding side got cpu stats during call, it seems like there is no way for stream decoding side to detect the CPU/GPU overload on decoding side.

**Comment by fippo** [comment]
the common approach here is to sum up the totalDecodeTime.

https://youtu.be/jlW1VdTjkbk?t=217 has a pretty good explanation.

**Comment by henbos** [comment]
+1 to what fippo said. To elaborate a bit:

For general CPU metrics I think that is a question outside of the WebRTC statistics API, since that has applications that reach far outside of WebRTC.

The internal "CPU overuse detection" in WebRTC, which is used to automatically decrease resolution (or frame rate depending on degradationPreference), is actually based on the ratio of time it takes to encode versus time in-between frames. So you should be able to achieve something very similar for the decode side based on totalDecodeTime and framesDecoded. That's probably your best bet for interop too and considering asking the SFU to send smaller streams is an application level decision I think letting the application handle all "decode overuse" logic makes the most sense and AFAIK the relevant metrics already exist. Or is something else missing that is specific to WebRTC?

**Comment by byterldp** [comment]
> +1 to what fippo said. To elaborate a bit:
> 
> For general CPU metrics I think that is a question outside of the WebRTC statistics API, since that has applications that reach far outside of WebRTC.
> 
> The internal "CPU overuse detection" in WebRTC, which is used to automatically decrease resolution (or frame rate depending on degradationPreference), is actually based on the ratio of time it takes to encode versus time in-between frames. So you should be able to achieve something very similar for the decode side based on totalDecodeTime and framesDecoded. That's probably your best bet for interop too and considering asking the SFU to send smaller streams is an application level decision I think letting the application handle all "decode overuse" logic makes the most sense and AFAIK the relevant metrics already exist. Or is something else missing that is specific to WebRTC?

Agree with you, its ok for application level decide overuse by calc average DecodeTime, thanks.

**Comment by henbos** [comment]
Alright cool then I'm closing this issue :)
