### ISSUE TITLE
Move RTCRtpReceivedRtpStreamStats.framesDropped to RTCInboundRtpStreamStats.

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#661]
It's only implemented in inbound-rtp, [not remote-inbound-rtp](https://wpt.fyi/results/webrtc-stats/supported-stats.html?label=experimental&label=master&aligned). Let's just move it?

**Comment by alvestrand** [comment]
It seems to be possible to implement this stat for remote-inbound-rtp when the relevant XR block (Frame Impairment Statistics Summary Block) is implemented. I don't think Chrome implements that block, but it would seem to be useful if a browser ever does. Mention it in -extensions?

**Comment by balazskreith** [comment]
There were a lot of metrics in RtcReceivedRtpStreamStats (packetsDiscarded, packetsRepaired, burstPacketsDiscarded, etc...), which were there because they can be calculated based on XR reports. now it is cleaned up and contains only the very essential that a receiver reports, except the `framesDropped`, which is specific to video. 
Wouldn't it make more sense to move to the inbound-rtp where the framesDecoded presented, or / move to [RTCRemoteInboundRtpStreamStats](https://www.w3.org/TR/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats) where the fractionLost is?!. Though moving to the latter one we have the same ambiguity as keeping it in RtcReceivedRtpStreamStats

**Comment by henbos** [comment]
The purpose of moving the metrics around is to make the spec more accurately reflect implementation status and implementer interest. So a lot of metrics are moved not because they don't make sense (they generally do make sense) but rather that nobody has bothered to implement them for several years and "there exists a definition for the metric" has not been considered a good enough reason for staffing it.

**Comment by vr000m** [comment]
I think in the extensions, it should reside in the `RTCRtpReceivedRtpStreamStats`, in case it is ever implemented as an XR block, it would be in the correct location.
