### ISSUE TITLE
Add field `fecPacketsSent` to RtcOutboundRtpStreamStats

### ISSUE THREAD

**Issue by balazskreith** [w3c/webrtc-stats#692]
Similar to the `RtcInboundRtpStreamStats`, where `fecPacketsReceived`, and `fecPacketsDiscarded` are present, wouldn't it make sense to add the `fecPacketsSent` to the outbound-rtp-stats, or it is implied that it can be calculated at the receiver side by summing up the provided two metrics?

**Comment by henbos** [comment]
outbound-rtp.fecPacketsSent did previously exist in the spec but it was [moved to webrtc-provisional-stats](https://w3c.github.io/webrtc-provisional-stats/#dom-rtcoutboundrtpstreamstats-fecpacketssent) because there was no implementer commitment for several years. The reasoning being we shouldn't bloat the spec with unimplemented metrics, that would prevent the spec from reaching Proposed Recommendation status. If implementation interest arises, we can always move metrics back, but nobody has offered to implement it.

**Comment by balazskreith** [comment]
That's fair. 
Why the `fecPacketsReceived` and `fecPacketsDiscarded` remained then at the receiver-side?

**Comment by henbos** [comment]
Because they've already been implemented by all browsers, see [WPT status](https://wpt.fyi/results/webrtc-stats/supported-stats.html?label=experimental&label=master&aligned).
