### ISSUE TITLE
add video totalFreezesDuration &totalPausesDuration etc to  standard getStats 

### ISSUE THREAD

**Issue by bdrtc** [w3c/webrtc-stats#695]
video totalFreezesDuration,totalPausesDuration relate call stats are not in standard getStats api call , its very important for stats overall video stall rate of a call , RTC system usually use reported stall rate drive or measure their qos optimization， we known chrome add video stall stats to [webrtc-provisional-stats](https://w3c.github.io/webrtc-provisional-stats/), but developer can't get it via api call.

**Comment by henbos** [comment]
@ssilkin, as the person who added totalFreezeDuration, totalPausesDuration (as well as totalFramesDuration and sumSquaredFrameDurations) can you comment?

I don't remember why we added them to webrtc-provisional-stats rather than webrtc-stats, but I'm guessing we didn't know how useful they would be at the time and put them there. Sounds like people find them useful, what is your experience?

Should we move these to the main spec and expose them to JavaScript or not?

**Comment by henbos** [comment]
(For context, these "non-standard" metrics are currently exposed to native apps and chrome://webrtc-internals/ page, but they need to be moved to the main spec document for us to expose them to JS)

**Comment by henbos** [comment]
Apparently this has been requested before: #609 
We should get a conclusion on this

**Comment by ssilkin** [comment]
I would vote for adding totalFreezesDuration and totalPausesDuration to the main spec and expose them to JavaScript. They proofed to be useful.

Regarding totalFramesDuration and sumSquaredFrameDurations. There were plans to deprecate those metrics in favour of total_inter_frame_delay and total_squared_inter_frame_delay: https://crbug.com/webrtc/11587

**Comment by henbos** [comment]
That makes sense, totalInterframeDelay and totalSquaredInterframeDelay are already in the main spec ([here](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalinterframedelay)).

I can write a PR to move totalFreezesDuration and totalPausesDuration to this spec.
