### ISSUE TITLE
Need consistent name for RTT estimate on RTCRTPStreamStats and on ICECandidatePair

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#74]
We currently have an RTT stat on a candidate pair, but the RTP spec defines a different RTT metric (based on RTCP and timestamp correlations).

Consider whether we should expose this too, and if so, how.

**Comment by vr000m** [comment]
@alvestrand we do have Rtt in OutboundStats:
```
dictionary RTCOutboundRTPStreamStats : RTCRTPStreamStats {
    unsigned long      packetsSent;
    unsigned long long bytesSent;
    double             targetBitrate;
    double             roundTripTime;
};
```

**Comment by alvestrand** [comment]
Oops. Sorry. Closing as "missed it".

**Comment by fippo** [comment]
which means (which caused this issue and confused me as well) that we now have one roundTripTime (on stream stats) and two "rtt" in https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatepairstats-currentrtt

For the sake of consistency either both should be abbreviated or none. I have no opinion which one ;-)

**Comment by vr000m** [comment]
we could change it to RTT. @alvestrand, @jan-ivar -- what do you think?

**Comment by alvestrand** [comment]
Reopening and renaming issue.
Stylistically, I prefer the longer name. But I'd prefer to go with whatever's implemented first. @ShijunS @jan-ivar?

**Comment by jan-ivar** [comment]
@vr000m  We [implement](https://dxr.mozilla.org/mozilla-central/rev/215f9686117673a2c914ed207bc7da9bb8d741ad/dom/webidl/RTCStatsReport.webidl#51) `mozRtt` in RTCInboundRTPStreamStats, since rtcp info is in the [opposite dictionary](http://stackoverflow.com/a/29840886/918910) . E.g.

```
{ "id": "outbound_rtcp_video_1",
 "timestamp": 1477343155549.51,
 "type": "inboundrtp", "isRemote": true,
 "mediaType": "video",
 "remoteId": "outbound_rtp_video_1",
 "ssrc": "892087744",
 "bytesReceived": 99076,
 "jitter": 0.289,
 "mozRtt": 1,
 "packetsLost": 0,
 "packetsReceived": 124 
}
```

How come you have it on RTCOutboundRTPStreamStats ?

You can get a dump in FF from https://jsfiddle.net/jib1/moz71L7h/

@alvestrand I have no strong preference on naming.

**Comment by alvestrand** [comment]
@jan-ivar my interpretation of RTT is that you compute it on the sender by comparing the time you get an RTCP RR for a given RTP timestamp with the time you sent that RTP timestamp (- the delta between packet reception and RTCP emission, which is part of the RR). This is a computation that can only be done at the sender.

I'm sure @vr000m will now jump out and correct my misapprehension....

**Comment by vr000m** [comment]
@alvestrand is correct. The RTT is calculated at the sender-side. By using the info in the RTCP RR. The calculation is explained in detail in RFC3550. 

RTT is calculated by subtracting the the sum of the two timestamps (LSR and DLSR) in RTCP RR from the reception time of the RTCP RR.

**Comment by ShijunS** [comment]
To echo what @vr000m said, Edge has "roundTripTime" in RTCOutboundRTPStreamStats on the sender side.  Naming wise, I'd prefer the longer name.

**Comment by vr000m** [comment]
I suppose no real change needed. I'll abbreviate the roundtriptime to RTT in the definition for the RTP metric, so that word search should find it.

**Comment by alvestrand** [comment]
If nobody's implemented the candidate pair RTT variables (sumRtt and currentRtt), I'd like to rename those to sumRoundTripTime and currentRoundTripTime.

**Comment by jan-ivar** [comment]
@vr000m , @alvestrand This is all sender-side. Isn't the important distinction instead that (calculations off) data from RTCP RR, normally go in the "remote" dictionary?

We can't have an RTT calculation without an RTCP RR, so it seemed logical to put it with the RTCP RR data, when we consider that RTCP RR's happen less frequently than local-only sampling:

E.g. from a local-loop test:

```js
// This one is calculated from RTCP RR data (received sender-side):
{ "id": "outbound_rtcp_video_1",
 "timestamp": 1477409522010.406, // Time is T + 0
 "type": "inboundrtp",
 "isRemote": true,
 "mediaType": "video",
 "remoteId": "outbound_rtp_video_1",
 "ssrc": "2107138979", "bytesReceived": 176175,
 "jitter": 0.479, "mozRtt": 1,
 "packetsLost": 0,
 "packetsReceived": 243
},
// This one is only about data going out, or about to go out (sender-side):
{ "id": "outbound_rtp_video_1",
 "timestamp": 1477409522019.865, // Time is T + 9.46 (newer!)
 "type": "outboundrtp",
 "bitrateMean": 309833,
 "bitrateStdDev": 79133.13772055294,
 "framerateMean": 30.4,
 "framerateStdDev": 0.547722557505166,
 "isRemote": false,
 "mediaType": "video",
 "remoteId": "outbound_rtcp_video_1",
 "ssrc": "2107138979",
 "bytesSent": 194721,
 "droppedFrames": 0,
 "packetsSent": 261
}
```

As you can see here, the RTCP data is older, because they only come in every 5 seconds or so, whereas sampling of sender-side data happens more frequently. The RTT calculation is as dated as the RTCP data, so it doesn't belong in the newer one IMHO.

**Comment by vr000m** [comment]
I was expecting the RTT to be in the  inbound remote and not the outbound local.

**Comment by jan-ivar** [comment]
@vr000m `"mozRtt": 1` is in the top one, which has `"type": "inboundrtp", "isRemote": true`, is that what you meant?

**Comment by alvestrand** [comment]
OK, let's move it.

**Comment by vr000m** [comment]
closing this issue because issue #78 covers this issue and PR #95 fixed the original concern.
