### ISSUE TITLE
Clarify RTCPeerConnectionStats's dataChannelsOpened/Closed description

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#79]
Current description: "Represents the number of unique datachannels [opened/closed]."

Only DataChannels that have been fully opened should increase the closed counter when closed, so that (opened - closed) = (currently open). It may be possible for a DataChannel to go from Connecting to Closing/Closed, skipping the Open state.

Also, should "datachannel" be written as "DataChannel" or "data channel" instead?

**Comment by henbos** [comment]
I think it is also unclear from the current description that these are not the counts of opened/closed data channels that exist but counts of channels that have at some point been opened or closed. I.e. if a channel is opened and then closed the counts are (opened: 1, closed: 1) and not (opened: 0, closed: 1)

**Comment by jesup** [comment]
The current wording would seem to include any datachannel opened from your end, and and channels opened from the other end (ondatachannel events); for close it would be similar - any explicitly closed (from either end), plus those that closed due to link failure.

I've always preferred "DataChannel" (or RTCDataChannel objects) which is specific, compared to "data channel" which is descriptive, but I don't have strong feelings on the subject so long as everything is clear.

**Comment by alvestrand** [comment]
I think we have to define the API events that correspond to incrementing the counters.

**Comment by vr000m** [comment]
Should we separate the counters for local and remote datachannels? Does anyone have thoughts on this?
